# -*- coding: utf-8 -*-
"""filter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gSteU7NIhnJFMjt9xS7FrfkMoA9JZxUw
"""

import pandas as pd
import math
# relevant object filter according to the distance from the car
def relevant_obj_filter(row):
    p_dist=[] # distance container
    midx=-100; # index of the relevant object initialization
    for i, obj in enumerate(row['objects']):
      if obj['Distance_X']!=0: # we don't need any data which is 0
         dist=math.sqrt(math.pow(obj['Distance_Y'],2)+math.pow(obj['Distance_X'],2))
         p_dist.append(dist) # add dist to a list
      else:
        p_dist.append(9999)  # if we have 0 x than we give it a big distance, because it a measure error
      midx=p_dist.index(min(p_dist)) # get the index of the min distance
    row['objects'][midx]['state']=True # set it to the relevant objext
    print(j)
    print(row['objects'][midx]['name'], row['objects'][midx]['state'])

for j, row in enumerate(dataset):
    relevant_obj_filter(row)